### ISSUE TITLE
variables skipped every 2nd lines

### ISSUE THREAD

**Issue by phradion** [buildo/sass-variables-loader#6]
```
$loaded1: 100px;

$loaded2: 100px;
$ignored: 111px;
$loaded3: 100px;
```

In above case, $ignored is not parsed while $loaded1, $loaded2 and $loaded3 are loaded into the module exports.

**Comment by giogonzo** [comment]
you're right, and tests were fundamentally broken.

Fixed in 9f2ae56ca85012cd8e020f5acc6ca239562bcb81 `v0.1.3`

Thanks for noticing :+1:
